package com.sottti.roller.coasters.presentation.design.system.colors.color

import androidx.compose.ui.graphics.Color

internal object ColorTokens {
    internal object Light {
        internal object StandardContrast {
            internal val primary = Color(0xFF466730)
            internal val onPrimary = Color(0xFFFFFFFF)
            internal val primaryContainer = Color(0xFFC7EEA9)
            internal val onPrimaryContainer = Color(0xFF2F4F1B)
            internal val secondary = Color(0xFF56624B)
            internal val onSecondary = Color(0xFFFFFFFF)
            internal val secondaryContainer = Color(0xFFD9E7CA)
            internal val onSecondaryContainer = Color(0xFF3E4A35)
            internal val tertiary = Color(0xFF386666)
            internal val onTertiary = Color(0xFFFFFFFF)
            internal val tertiaryContainer = Color(0xFFBBECEB)
            internal val onTertiaryContainer = Color(0xFF1E4E4E)
            internal val error = Color(0xFFBA1A1A)
            internal val onError = Color(0xFFFFFFFF)
            internal val errorContainer = Color(0xFFFFDAD6)
            internal val onErrorContainer = Color(0xFF93000A)
            internal val background = Color(0xFFF8FAF0)
            internal val onBackground = Color(0xFF191D16)
            internal val surface = Color(0xFFF8FAF0)
            internal val onSurface = Color(0xFF191D16)
            internal val surfaceVariant = Color(0xFFE0E4D6)
            internal val onSurfaceVariant = Color(0xFF43483E)
            internal val outline = Color(0xFF74796D)
            internal val outlineVariant = Color(0xFFC4C8BB)
            internal val scrim = Color(0xFF000000)
            internal val inverseSurface = Color(0xFF2E312A)
            internal val inverseOnSurface = Color(0xFFF0F2E7)
            internal val inversePrimary = Color(0xFFABD28F)
            internal val surfaceDim = Color(0xFFD9DBD1)
            internal val surfaceBright = Color(0xFFF8FAF0)
            internal val surfaceContainerLowest = Color(0xFFFFFFFF)
            internal val surfaceContainerLow = Color(0xFFF3F5EA)
            internal val surfaceContainer = Color(0xFFEDEFE4)
            internal val surfaceContainerHigh = Color(0xFFE7E9DF)
            internal val surfaceContainerHighest = Color(0xFFE1E4D9)
        }

        internal object MediumContrast {
            internal val primaryMediumContrast = Color(0xFF1F3D0B)
            internal val onPrimaryMediumContrast = Color(0xFFFFFFFF)
            internal val primaryContainerMediumContrast = Color(0xFF54763E)
            internal val onPrimaryContainerMediumContrast = Color(0xFFFFFFFF)
            internal val secondaryMediumContrast = Color(0xFF2E3A25)
            internal val onSecondaryMediumContrast = Color(0xFFFFFFFF)
            internal val secondaryContainerMediumContrast = Color(0xFF647159)
            internal val onSecondaryContainerMediumContrast = Color(0xFFFFFFFF)
            internal val tertiaryMediumContrast = Color(0xFF073D3D)
            internal val onTertiaryMediumContrast = Color(0xFFFFFFFF)
            internal val tertiaryContainerMediumContrast = Color(0xFF477574)
            internal val onTertiaryContainerMediumContrast = Color(0xFFFFFFFF)
            internal val errorMediumContrast = Color(0xFF740006)
            internal val onErrorMediumContrast = Color(0xFFFFFFFF)
            internal val errorContainerMediumContrast = Color(0xFFCF2C27)
            internal val onErrorContainerMediumContrast = Color(0xFFFFFFFF)
            internal val backgroundMediumContrast = Color(0xFFF8FAF0)
            internal val onBackgroundMediumContrast = Color(0xFF191D16)
            internal val surfaceMediumContrast = Color(0xFFF8FAF0)
            internal val onSurfaceMediumContrast = Color(0xFF0F120C)
            internal val surfaceVariantMediumContrast = Color(0xFFE0E4D6)
            internal val onSurfaceVariantMediumContrast = Color(0xFF33382E)
            internal val outlineMediumContrast = Color(0xFF4F5449)
            internal val outlineVariantMediumContrast = Color(0xFF6A6F63)
            internal val scrimMediumContrast = Color(0xFF000000)
            internal val inverseSurfaceMediumContrast = Color(0xFF2E312A)
            internal val inverseOnSurfaceMediumContrast = Color(0xFFF0F2E7)
            internal val inversePrimaryMediumContrast = Color(0xFFABD28F)
            internal val surfaceDimMediumContrast = Color(0xFFC5C8BE)
            internal val surfaceBrightMediumContrast = Color(0xFFF8FAF0)
            internal val surfaceContainerLowestMediumContrast = Color(0xFFFFFFFF)
            internal val surfaceContainerLowMediumContrast = Color(0xFFF3F5EA)
            internal val surfaceContainerMediumContrast = Color(0xFFE7E9DF)
            internal val surfaceContainerHighMediumContrast = Color(0xFFDCDED4)
            internal val surfaceContainerHighestMediumContrast = Color(0xFFD0D3C8)
        }

        internal object HighContrast {
            internal val primaryHighContrast = Color(0xFF153302)
            internal val onPrimaryHighContrast = Color(0xFFFFFFFF)
            internal val primaryContainerHighContrast = Color(0xFF31511D)
            internal val onPrimaryContainerHighContrast = Color(0xFFFFFFFF)
            internal val secondaryHighContrast = Color(0xFF242F1C)
            internal val onSecondaryHighContrast = Color(0xFFFFFFFF)
            internal val secondaryContainerHighContrast = Color(0xFF414D37)
            internal val onSecondaryContainerHighContrast = Color(0xFFFFFFFF)
            internal val tertiaryHighContrast = Color(0xFF003232)
            internal val onTertiaryHighContrast = Color(0xFFFFFFFF)
            internal val tertiaryContainerHighContrast = Color(0xFF215050)
            internal val onTertiaryContainerHighContrast = Color(0xFFFFFFFF)
            internal val errorHighContrast = Color(0xFF600004)
            internal val onErrorHighContrast = Color(0xFFFFFFFF)
            internal val errorContainerHighContrast = Color(0xFF98000A)
            internal val onErrorContainerHighContrast = Color(0xFFFFFFFF)
            internal val backgroundHighContrast = Color(0xFFF8FAF0)
            internal val onBackgroundHighContrast = Color(0xFF191D16)
            internal val surfaceHighContrast = Color(0xFFF8FAF0)
            internal val onSurfaceHighContrast = Color(0xFF000000)
            internal val surfaceVariantHighContrast = Color(0xFFE0E4D6)
            internal val onSurfaceVariantHighContrast = Color(0xFF000000)
            internal val outlineHighContrast = Color(0xFF292E24)
            internal val outlineVariantHighContrast = Color(0xFF464B40)
            internal val scrimHighContrast = Color(0xFF000000)
            internal val inverseSurfaceHighContrast = Color(0xFF2E312A)
            internal val inverseOnSurfaceHighContrast = Color(0xFFFFFFFF)
            internal val inversePrimaryHighContrast = Color(0xFFABD28F)
            internal val surfaceDimHighContrast = Color(0xFFB7BAB0)
            internal val surfaceBrightHighContrast = Color(0xFFF8FAF0)
            internal val surfaceContainerLowestHighContrast = Color(0xFFFFFFFF)
            internal val surfaceContainerLowHighContrast = Color(0xFFF0F2E7)
            internal val surfaceContainerHighContrast = Color(0xFFE1E4D9)
            internal val surfaceContainerHighHighContrast = Color(0xFFD3D5CB)
            internal val surfaceContainerHighestHighContrast = Color(0xFFC5C8BE)
        }
    }

    internal object Dark {
        internal object StandardContrast {
            internal val primary = Color(0xFFABD28F)
            internal val onPrimary = Color(0xFF193706)
            internal val primaryContainer = Color(0xFF2F4F1B)
            internal val onPrimaryContainer = Color(0xFFC7EEA9)
            internal val secondary = Color(0xFFBDCBAF)
            internal val onSecondary = Color(0xFF283420)
            internal val secondaryContainer = Color(0xFF3E4A35)
            internal val onSecondaryContainer = Color(0xFFD9E7CA)
            internal val tertiary = Color(0xFFA0CFCF)
            internal val onTertiary = Color(0xFF003737)
            internal val tertiaryContainer = Color(0xFF1E4E4E)
            internal val onTertiaryContainer = Color(0xFFBBECEB)
            internal val error = Color(0xFFFFB4AB)
            internal val onError = Color(0xFF690005)
            internal val errorContainer = Color(0xFF93000A)
            internal val onErrorContainer = Color(0xFFFFDAD6)
            internal val background = Color(0xFF11140E)
            internal val onBackground = Color(0xFFE1E4D9)
            internal val surface = Color(0xFF11140E)
            internal val onSurface = Color(0xFFFF00FF)
            internal val surfaceVariant = Color(0xFF43483E)
            internal val onSurfaceVariant = Color(0xFFC4C8BB)
            internal val outline = Color(0xFF8E9286)
            internal val outlineVariant = Color(0xFF43483E)
            internal val scrim = Color(0xFF000000)
            internal val inverseSurface = Color(0xFFE1E4D9)
            internal val inverseOnSurface = Color(0xFF2E312A)
            internal val inversePrimary = Color(0xFF466730)
            internal val surfaceDim = Color(0xFF11140E)
            internal val surfaceBright = Color(0xFF373A33)
            internal val surfaceContainerLowest = Color(0xFF0C0F09)
            internal val surfaceContainerLow = Color(0xFF191D16)
            internal val surfaceContainer = Color(0xFF1D211A)
            internal val surfaceContainerHigh = Color(0xFF282B24)
            internal val surfaceContainerHighest = Color(0xFF33362F)
        }

        internal object MediumContrast {
            internal val primaryMediumContrast = Color(0xFFC1E8A3)
            internal val onPrimaryMediumContrast = Color(0xFF0F2C00)
            internal val primaryContainerMediumContrast = Color(0xFF779B5E)
            internal val onPrimaryContainerMediumContrast = Color(0xFF000000)
            internal val secondaryMediumContrast = Color(0xFFD3E1C4)
            internal val onSecondaryMediumContrast = Color(0xFF1E2916)
            internal val secondaryContainerMediumContrast = Color(0xFF88957B)
            internal val onSecondaryContainerMediumContrast = Color(0xFF000000)
            internal val tertiaryMediumContrast = Color(0xFFB5E5E5)
            internal val onTertiaryMediumContrast = Color(0xFF002B2B)
            internal val tertiaryContainerMediumContrast = Color(0xFF6B9998)
            internal val onTertiaryContainerMediumContrast = Color(0xFF000000)
            internal val errorMediumContrast = Color(0xFFFFD2CC)
            internal val onErrorMediumContrast = Color(0xFF540003)
            internal val errorContainerMediumContrast = Color(0xFFFF5449)
            internal val onErrorContainerMediumContrast = Color(0xFF000000)
            internal val backgroundMediumContrast = Color(0xFF11140E)
            internal val onBackgroundMediumContrast = Color(0xFFE1E4D9)
            internal val surfaceMediumContrast = Color(0xFF11140E)
            internal val onSurfaceMediumContrast = Color(0xFFFFFFFF)
            internal val surfaceVariantMediumContrast = Color(0xFF43483E)
            internal val onSurfaceVariantMediumContrast = Color(0xFFDADED0)
            internal val outlineMediumContrast = Color(0xFFAFB4A7)
            internal val outlineVariantMediumContrast = Color(0xFF8D9286)
            internal val scrimMediumContrast = Color(0xFF000000)
            internal val inverseSurfaceMediumContrast = Color(0xFFE1E4D9)
            internal val inverseOnSurfaceMediumContrast = Color(0xFF282B24)
            internal val inversePrimaryMediumContrast = Color(0xFF30501C)
            internal val surfaceDimMediumContrast = Color(0xFF11140E)
            internal val surfaceBrightMediumContrast = Color(0xFF42463E)
            internal val surfaceContainerLowestMediumContrast = Color(0xFF060804)
            internal val surfaceContainerLowMediumContrast = Color(0xFF1B1F18)
            internal val surfaceContainerMediumContrast = Color(0xFF262922)
            internal val surfaceContainerHighMediumContrast = Color(0xFF30342D)
            internal val surfaceContainerHighestMediumContrast = Color(0xFF3B3F37)
        }

        internal object HighContrast {
            internal val primaryHighContrast = Color(0xFFD4FCB6)
            internal val onPrimaryHighContrast = Color(0xFF000000)
            internal val primaryContainerHighContrast = Color(0xFFA7CE8C)
            internal val onPrimaryContainerHighContrast = Color(0xFF030E00)
            internal val secondaryHighContrast = Color(0xFFE7F5D7)
            internal val onSecondaryHighContrast = Color(0xFF000000)
            internal val secondaryContainerHighContrast = Color(0xFFB9C7AB)
            internal val onSecondaryContainerHighContrast = Color(0xFF050E02)
            internal val tertiaryHighContrast = Color(0xFFC9F9F8)
            internal val onTertiaryHighContrast = Color(0xFF000000)
            internal val tertiaryContainerHighContrast = Color(0xFF9CCBCB)
            internal val onTertiaryContainerHighContrast = Color(0xFF000E0E)
            internal val errorHighContrast = Color(0xFFFFECE9)
            internal val onErrorHighContrast = Color(0xFF000000)
            internal val errorContainerHighContrast = Color(0xFFFFAEA4)
            internal val onErrorContainerHighContrast = Color(0xFF220001)
            internal val backgroundHighContrast = Color(0xFF11140E)
            internal val onBackgroundHighContrast = Color(0xFFE1E4D9)
            internal val surfaceHighContrast = Color(0xFF11140E)
            internal val onSurfaceHighContrast = Color(0xFFFFFFFF)
            internal val surfaceVariantHighContrast = Color(0xFF43483E)
            internal val onSurfaceVariantHighContrast = Color(0xFFFFFFFF)
            internal val outlineHighContrast = Color(0xFFEDF2E3)
            internal val outlineVariantHighContrast = Color(0xFFC0C4B7)
            internal val scrimHighContrast = Color(0xFF000000)
            internal val inverseSurfaceHighContrast = Color(0xFFE1E4D9)
            internal val inverseOnSurfaceHighContrast = Color(0xFF000000)
            internal val inversePrimaryHighContrast = Color(0xFF30501C)
            internal val surfaceDimHighContrast = Color(0xFF11140E)
            internal val surfaceBrightHighContrast = Color(0xFF4E5149)
            internal val surfaceContainerLowestHighContrast = Color(0xFF000000)
            internal val surfaceContainerLowHighContrast = Color(0xFF1D211A)
            internal val surfaceContainerHighContrast = Color(0xFF2E312A)
            internal val surfaceContainerHighHighContrast = Color(0xFF393C35)
            internal val surfaceContainerHighestHighContrast = Color(0xFF454840)
        }
    }
}