package com.sottti.roller.coasters.presentation.design.system.colors.color

import androidx.compose.ui.graphics.Color

internal object ColorTokens {
    internal object Light {
        internal object StandardContrast {
            internal val primary = Color(0xFF415F91)
            internal val onPrimary = Color(0xFFFFFFFF)
            internal val primaryContainer = Color(0xFFD6E3FF)
            internal val onPrimaryContainer = Color(0xFF284777)
            internal val secondary = Color(0xFF565F71)
            internal val onSecondary = Color(0xFFFFFFFF)
            internal val secondaryContainer = Color(0xFFDAE2F9)
            internal val onSecondaryContainer = Color(0xFF3E4759)
            internal val tertiary = Color(0xFF705575)
            internal val onTertiary = Color(0xFFFFFFFF)
            internal val tertiaryContainer = Color(0xFFFAD8FD)
            internal val onTertiaryContainer = Color(0xFF573E5C)
            internal val error = Color(0xFFBA1A1A)
            internal val onError = Color(0xFFFFFFFF)
            internal val errorContainer = Color(0xFFFFDAD6)
            internal val onErrorContainer = Color(0xFF93000A)
            internal val background = Color(0xFFF9F9FF)
            internal val onBackground = Color(0xFF191C20)
            internal val surface = Color(0xFFF9F9FF)
            internal val onSurface = Color(0xFF191C20)
            internal val surfaceVariant = Color(0xFFE0E2EC)
            internal val onSurfaceVariant = Color(0xFF44474E)
            internal val outline = Color(0xFF74777F)
            internal val outlineVariant = Color(0xFFC4C6D0)
            internal val scrim = Color(0xFF000000)
            internal val inverseSurface = Color(0xFF2E3036)
            internal val inverseOnSurface = Color(0xFFF0F0F7)
            internal val inversePrimary = Color(0xFFAAC7FF)
            internal val surfaceDim = Color(0xFFD9D9E0)
            internal val surfaceBright = Color(0xFFF9F9FF)
            internal val surfaceContainerLowest = Color(0xFFFFFFFF)
            internal val surfaceContainerLow = Color(0xFFF3F3FA)
            internal val surfaceContainer = Color(0xFFEDEDF4)
            internal val surfaceContainerHigh = Color(0xFFE7E8EE)
            internal val surfaceContainerHighest = Color(0xFFE2E2E9)
        }

        internal object MediumContrast {
            internal val primaryMediumContrast = Color(0xFF133665)
            internal val onPrimaryMediumContrast = Color(0xFFFFFFFF)
            internal val primaryContainerMediumContrast = Color(0xFF506DA0)
            internal val onPrimaryContainerMediumContrast = Color(0xFFFFFFFF)
            internal val secondaryMediumContrast = Color(0xFF2E3647)
            internal val onSecondaryMediumContrast = Color(0xFFFFFFFF)
            internal val secondaryContainerMediumContrast = Color(0xFF646D80)
            internal val onSecondaryContainerMediumContrast = Color(0xFFFFFFFF)
            internal val tertiaryMediumContrast = Color(0xFF452E4A)
            internal val onTertiaryMediumContrast = Color(0xFFFFFFFF)
            internal val tertiaryContainerMediumContrast = Color(0xFF7F6484)
            internal val onTertiaryContainerMediumContrast = Color(0xFFFFFFFF)
            internal val errorMediumContrast = Color(0xFF740006)
            internal val onErrorMediumContrast = Color(0xFFFFFFFF)
            internal val errorContainerMediumContrast = Color(0xFFCF2C27)
            internal val onErrorContainerMediumContrast = Color(0xFFFFFFFF)
            internal val backgroundMediumContrast = Color(0xFFF9F9FF)
            internal val onBackgroundMediumContrast = Color(0xFF191C20)
            internal val surfaceMediumContrast = Color(0xFFF9F9FF)
            internal val onSurfaceMediumContrast = Color(0xFF0F1116)
            internal val surfaceVariantMediumContrast = Color(0xFFE0E2EC)
            internal val onSurfaceVariantMediumContrast = Color(0xFF33363E)
            internal val outlineMediumContrast = Color(0xFF4F525A)
            internal val outlineVariantMediumContrast = Color(0xFF6A6D75)
            internal val scrimMediumContrast = Color(0xFF000000)
            internal val inverseSurfaceMediumContrast = Color(0xFF2E3036)
            internal val inverseOnSurfaceMediumContrast = Color(0xFFF0F0F7)
            internal val inversePrimaryMediumContrast = Color(0xFFAAC7FF)
            internal val surfaceDimMediumContrast = Color(0xFFC5C6CD)
            internal val surfaceBrightMediumContrast = Color(0xFFF9F9FF)
            internal val surfaceContainerLowestMediumContrast = Color(0xFFFFFFFF)
            internal val surfaceContainerLowMediumContrast = Color(0xFFF3F3FA)
            internal val surfaceContainerMediumContrast = Color(0xFFE7E8EE)
            internal val surfaceContainerHighMediumContrast = Color(0xFFDCDCE3)
            internal val surfaceContainerHighestMediumContrast = Color(0xFFD1D1D8)
        }

        internal object HighContrast {
            internal val primaryHighContrast = Color(0xFF032B5B)
            internal val onPrimaryHighContrast = Color(0xFFFFFFFF)
            internal val primaryContainerHighContrast = Color(0xFF2A497A)
            internal val onPrimaryContainerHighContrast = Color(0xFFFFFFFF)
            internal val secondaryHighContrast = Color(0xFF232C3D)
            internal val onSecondaryHighContrast = Color(0xFFFFFFFF)
            internal val secondaryContainerHighContrast = Color(0xFF41495B)
            internal val onSecondaryContainerHighContrast = Color(0xFFFFFFFF)
            internal val tertiaryHighContrast = Color(0xFF3A2440)
            internal val onTertiaryHighContrast = Color(0xFFFFFFFF)
            internal val tertiaryContainerHighContrast = Color(0xFF59405E)
            internal val onTertiaryContainerHighContrast = Color(0xFFFFFFFF)
            internal val errorHighContrast = Color(0xFF600004)
            internal val onErrorHighContrast = Color(0xFFFFFFFF)
            internal val errorContainerHighContrast = Color(0xFF98000A)
            internal val onErrorContainerHighContrast = Color(0xFFFFFFFF)
            internal val backgroundHighContrast = Color(0xFFF9F9FF)
            internal val onBackgroundHighContrast = Color(0xFF191C20)
            internal val surfaceHighContrast = Color(0xFFF9F9FF)
            internal val onSurfaceHighContrast = Color(0xFF000000)
            internal val surfaceVariantHighContrast = Color(0xFFE0E2EC)
            internal val onSurfaceVariantHighContrast = Color(0xFF000000)
            internal val outlineHighContrast = Color(0xFF292C33)
            internal val outlineVariantHighContrast = Color(0xFF464951)
            internal val scrimHighContrast = Color(0xFF000000)
            internal val inverseSurfaceHighContrast = Color(0xFF2E3036)
            internal val inverseOnSurfaceHighContrast = Color(0xFFFFFFFF)
            internal val inversePrimaryHighContrast = Color(0xFFAAC7FF)
            internal val surfaceDimHighContrast = Color(0xFFB8B8BF)
            internal val surfaceBrightHighContrast = Color(0xFFF9F9FF)
            internal val surfaceContainerLowestHighContrast = Color(0xFFFFFFFF)
            internal val surfaceContainerLowHighContrast = Color(0xFFF0F0F7)
            internal val surfaceContainerHighContrast = Color(0xFFE2E2E9)
            internal val surfaceContainerHighHighContrast = Color(0xFFD3D4DB)
            internal val surfaceContainerHighestHighContrast = Color(0xFFC5C6CD)
        }
    }

    internal object Dark {
        internal object StandardContrast {
            internal val primary = Color(0xFFAAC7FF)
            internal val onPrimary = Color(0xFF0A305F)
            internal val primaryContainer = Color(0xFF284777)
            internal val onPrimaryContainer = Color(0xFFD6E3FF)
            internal val secondary = Color(0xFFBEC6DC)
            internal val onSecondary = Color(0xFF283141)
            internal val secondaryContainer = Color(0xFF3E4759)
            internal val onSecondaryContainer = Color(0xFFDAE2F9)
            internal val tertiary = Color(0xFFDDBCE0)
            internal val onTertiary = Color(0xFF3F2844)
            internal val tertiaryContainer = Color(0xFF573E5C)
            internal val onTertiaryContainer = Color(0xFFFAD8FD)
            internal val error = Color(0xFFFFB4AB)
            internal val onError = Color(0xFF690005)
            internal val errorContainer = Color(0xFF93000A)
            internal val onErrorContainer = Color(0xFFFFDAD6)
            internal val background = Color(0xFF111318)
            internal val onBackground = Color(0xFFE2E2E9)
            internal val surface = Color(0xFF111318)
            internal val onSurface = Color(0xFFE2E2E9)
            internal val surfaceVariant = Color(0xFF44474E)
            internal val onSurfaceVariant = Color(0xFFC4C6D0)
            internal val outline = Color(0xFF8E9099)
            internal val outlineVariant = Color(0xFF44474E)
            internal val scrim = Color(0xFF000000)
            internal val inverseSurface = Color(0xFFE2E2E9)
            internal val inverseOnSurface = Color(0xFF2E3036)
            internal val inversePrimary = Color(0xFF415F91)
            internal val surfaceDim = Color(0xFF111318)
            internal val surfaceBright = Color(0xFF37393E)
            internal val surfaceContainerLowest = Color(0xFF0C0E13)
            internal val surfaceContainerLow = Color(0xFF191C20)
            internal val surfaceContainer = Color(0xFF1D2024)
            internal val surfaceContainerHigh = Color(0xFF282A2F)
            internal val surfaceContainerHighest = Color(0xFF33353A)
        }

        internal object MediumContrast {
            internal val primaryMediumContrast = Color(0xFFCDDDFF)
            internal val onPrimaryMediumContrast = Color(0xFF002551)
            internal val primaryContainerMediumContrast = Color(0xFF7491C7)
            internal val onPrimaryContainerMediumContrast = Color(0xFF000000)
            internal val secondaryMediumContrast = Color(0xFFD4DCF2)
            internal val onSecondaryMediumContrast = Color(0xFF1D2636)
            internal val secondaryContainerMediumContrast = Color(0xFF8891A5)
            internal val onSecondaryContainerMediumContrast = Color(0xFF000000)
            internal val tertiaryMediumContrast = Color(0xFFF3D2F7)
            internal val onTertiaryMediumContrast = Color(0xFF331D39)
            internal val tertiaryContainerMediumContrast = Color(0xFFA487A9)
            internal val onTertiaryContainerMediumContrast = Color(0xFF000000)
            internal val errorMediumContrast = Color(0xFFFFD2CC)
            internal val onErrorMediumContrast = Color(0xFF540003)
            internal val errorContainerMediumContrast = Color(0xFFFF5449)
            internal val onErrorContainerMediumContrast = Color(0xFF000000)
            internal val backgroundMediumContrast = Color(0xFF111318)
            internal val onBackgroundMediumContrast = Color(0xFFE2E2E9)
            internal val surfaceMediumContrast = Color(0xFF111318)
            internal val onSurfaceMediumContrast = Color(0xFFFFFFFF)
            internal val surfaceVariantMediumContrast = Color(0xFF44474E)
            internal val onSurfaceVariantMediumContrast = Color(0xFFDADCE6)
            internal val outlineMediumContrast = Color(0xFFAFB2BB)
            internal val outlineVariantMediumContrast = Color(0xFF8E9099)
            internal val scrimMediumContrast = Color(0xFF000000)
            internal val inverseSurfaceMediumContrast = Color(0xFFE2E2E9)
            internal val inverseOnSurfaceMediumContrast = Color(0xFF282A2F)
            internal val inversePrimaryMediumContrast = Color(0xFF294878)
            internal val surfaceDimMediumContrast = Color(0xFF111318)
            internal val surfaceBrightMediumContrast = Color(0xFF43444A)
            internal val surfaceContainerLowestMediumContrast = Color(0xFF06070C)
            internal val surfaceContainerLowMediumContrast = Color(0xFF1B1E22)
            internal val surfaceContainerMediumContrast = Color(0xFF26282D)
            internal val surfaceContainerHighMediumContrast = Color(0xFF313238)
            internal val surfaceContainerHighestMediumContrast = Color(0xFF3C3E43)
        }

        internal object HighContrast {
            internal val primaryHighContrast = Color(0xFFEBF0FF)
            internal val onPrimaryHighContrast = Color(0xFF000000)
            internal val primaryContainerHighContrast = Color(0xFFA6C3FC)
            internal val onPrimaryContainerHighContrast = Color(0xFF000B20)
            internal val secondaryHighContrast = Color(0xFFEBF0FF)
            internal val onSecondaryHighContrast = Color(0xFF000000)
            internal val secondaryContainerHighContrast = Color(0xFFBAC3D8)
            internal val onSecondaryContainerHighContrast = Color(0xFF030B1A)
            internal val tertiaryHighContrast = Color(0xFFFFE9FF)
            internal val onTertiaryHighContrast = Color(0xFF000000)
            internal val tertiaryContainerHighContrast = Color(0xFFD8B8DC)
            internal val onTertiaryContainerHighContrast = Color(0xFF16041D)
            internal val errorHighContrast = Color(0xFFFFECE9)
            internal val onErrorHighContrast = Color(0xFF000000)
            internal val errorContainerHighContrast = Color(0xFFFFAEA4)
            internal val onErrorContainerHighContrast = Color(0xFF220001)
            internal val backgroundHighContrast = Color(0xFF111318)
            internal val onBackgroundHighContrast = Color(0xFFE2E2E9)
            internal val surfaceHighContrast = Color(0xFF111318)
            internal val onSurfaceHighContrast = Color(0xFFFFFFFF)
            internal val surfaceVariantHighContrast = Color(0xFF44474E)
            internal val onSurfaceVariantHighContrast = Color(0xFFFFFFFF)
            internal val outlineHighContrast = Color(0xFFEEEFF9)
            internal val outlineVariantHighContrast = Color(0xFFC0C2CC)
            internal val scrimHighContrast = Color(0xFF000000)
            internal val inverseSurfaceHighContrast = Color(0xFFE2E2E9)
            internal val inverseOnSurfaceHighContrast = Color(0xFF000000)
            internal val inversePrimaryHighContrast = Color(0xFF294878)
            internal val surfaceDimHighContrast = Color(0xFF111318)
            internal val surfaceBrightHighContrast = Color(0xFF4E5056)
            internal val surfaceContainerLowestHighContrast = Color(0xFF000000)
            internal val surfaceContainerLowHighContrast = Color(0xFF1D2024)
            internal val surfaceContainerHighContrast = Color(0xFF2E3036)
            internal val surfaceContainerHighHighContrast = Color(0xFF393B41)
            internal val surfaceContainerHighestHighContrast = Color(0xFF45474C)
        }
    }
}