name: CI

on:
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3

      - name: Setup local.properties with Maps API Key
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> local.properties

      - name: Validate Gradle Wrapper
        run: ./gradlew --version

      - name: Assemble Debug
        run: ./gradlew assembleDebug --stacktrace --no-daemon

  jvm-tests:
    name: JVM Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3

      - name: Setup local.properties with Maps API Key
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> local.properties

      - name: Validate Gradle Wrapper
        run: ./gradlew --version

      - name: Run JVM Tests
        run: ./gradlew testDebugUnitTest --stacktrace --no-daemon